Repository Qiskit/qiskit-addon-aqc-tensor, pull requests merged in 2024-11, with the labels that each got.

#9 Replace `get_loss_fn` with `tnoptimizer_objective_kwargs`
  docs/how-tos/01_quimb_tnoptimizer.ipynb
  qiskit_addon_aqc_tensor/simulation/quimb/__init__.py
Labels: quimb

#12 Accept any quimb tensor network as target, not only circuits.
  qiskit_addon_aqc_tensor/simulation/quimb/__init__.py
Labels: quimb

#13 Rename `QuimbConversionContext` -> `QiskitQuimbConversionContext`
  qiskit_addon_aqc_tensor/simulation/quimb/__init__.py
Labels: quimb

#10 Provide option to assume zero initial state in ansatz generation
  qiskit_addon_aqc_tensor/ansatz_generation.py
  test/test_ansatz_generation.py
  test/test_aqc_workflows.py
Labels: enhancement, ansatz generation

#14 Add `parameter_name` argument to `generate_ansatz_from_circuit`
  qiskit_addon_aqc_tensor/ansatz_generation.py
Labels: enhancement, ansatz generation

#16 Update documentation for initial release
  INSTALL.rst
  docs/explanation/index.rst
  qiskit_addon_aqc_tensor/ansatz_generation.py
  qiskit_addon_aqc_tensor/objective.py
  qiskit_addon_aqc_tensor/simulation/abstract.py
  qiskit_addon_aqc_tensor/simulation/aer/state.py
Labels: documentation

#17 Refresh the tutorial (quick pass over it)
  docs/tutorials/01_basic_workflow.ipynb
  docs/tutorials/01_initial_state_aqc.ipynb
Labels: documentation

#18 Doc revisions
  docs/explanation/index.rst
  docs/tutorials/01_initial_state_aqc.ipynb
  releasenotes/config.yaml
Labels: documentation, stable backport potential

#22 More documentation updates
  docs/tutorials/01_initial_state_aqc.ipynb
  qiskit_addon_aqc_tensor/ansatz_generation.py
Labels: documentation, stable backport potential

#24 Test against the development version of more packages
  .github/workflows/test_development_versions.yml
Labels: ci-cd

#20 Pass `GITHUB_BASE_REF` and `GITHUB_REF_NAME` in docs tox environment
  tox.ini
Labels: documentation, stable backport potential

#23 Rephrase tutorial as step 1 of a Qiskit pattern
  docs/tutorials/01_initial_state_aqc.ipynb
Labels: documentation, stable backport potential

#26 Fix development version tests
  .github/workflows/test_development_versions.yml
Labels: stable backport potential

#27 Add autograd as a suggested quimb backend
  pyproject.toml
  test/conftest.py
Labels: quimb, tests, stable backport potential

#30 Replace pydocstyle with Ruff
  docs/conf.py
  pyproject.toml
  qiskit_addon_aqc_tensor/ansatz_generation.py
  qiskit_addon_aqc_tensor/objective.py
  qiskit_addon_aqc_tensor/simulation/__init__.py
  qiskit_addon_aqc_tensor/simulation/abstract.py
  qiskit_addon_aqc_tensor/simulation/aer/simulation.py
  qiskit_addon_aqc_tensor/simulation/explicit_gradient.py
  qiskit_addon_aqc_tensor/simulation/quimb/__init__.py
  tox.ini
Labels: stable backport potential

#32 Move kahypar from notebook-dependencies to quimb deps
  pyproject.toml
Labels: dependencies, stable backport potential

#29 Reorganize docs
  docs/_templates/autosummary/class.rst
  docs/apidocs/ansatz_generation.rst
  docs/apidocs/index.rst
  docs/apidocs/objective.rst
  docs/apidocs/simulation-aer.rst
  docs/apidocs/simulation-quimb.rst
  docs/apidocs/simulation.rst
  docs/conf.py
  qiskit_addon_aqc_tensor/__init__.py
  qiskit_addon_aqc_tensor/ansatz_generation.py
  qiskit_addon_aqc_tensor/objective.py
  qiskit_addon_aqc_tensor/simulation/__init__.py
  qiskit_addon_aqc_tensor/simulation/aer/__init__.py
  qiskit_addon_aqc_tensor/simulation/quimb/__init__.py
  tox.ini
Labels: documentation, stable backport potential

#33 Document `OneMinusFidelity.__call__`
  docs/apidocs/objective.rst
Labels: stable backport potential

#36 Fix imports according to development version of qiskit-quimb
  qiskit_addon_aqc_tensor/simulation/quimb/__init__.py
Labels: bug, quimb, stable backport potential

#40 Add release note for #36
  releasenotes/notes/qiskit-quimb-import-38826e52ff577787.yaml
Labels: stable backport potential

#39 Test all python versions on macOS
  .github/workflows/test_latest_versions.yml
Labels: ci-cd

#38 Install kahypar on macOS w/ python 3.12 since there are now wheels
  pyproject.toml
Labels: dependencies, quimb

#25 Add additional tests to bring up coverage
  qiskit_addon_aqc_tensor/simulation/abstract.py
  qiskit_addon_aqc_tensor/simulation/aer/simulation.py
  qiskit_addon_aqc_tensor/simulation/quimb/__init__.py
  test/simulation/quimb/test_quimb_backend.py
  test/test_ansatz_generation.py
  tox.ini
Labels: tests
